import { TokenInfo } from './types'

export const tokensToDisplayStub: TokenInfo[] = [
  {
    tokenTicker: 'BANANA',
    tokenPrice: 0.476,
    percentChange: -3.6,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/BANANA.svg',
  },
  {
    tokenTicker: 'BTC',
    tokenPrice: 42281,
    percentChange: -0.3,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/BTCB.svg',
  },
  {
    tokenTicker: 'ETH',
    tokenPrice: 2901.83,
    percentChange: 0.2,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/ETH.svg',
  },
  {
    tokenTicker: 'BNB',
    tokenPrice: 43000,
    percentChange: -0.1,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/BNB.svg',
  },
  {
    tokenTicker: 'DOGE',
    tokenPrice: 0.14,
    percentChange: -5.7,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/DOGE.svg',
  },
  {
    tokenTicker: 'XRP',
    tokenPrice: 0.79,
    percentChange: -2.5,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/XRP.svg',
  },
  {
    tokenTicker: 'AAVE',
    tokenPrice: 155.55,
    percentChange: -2.6,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/AAVE.svg',
  },
  {
    tokenTicker: 'MATIC',
    tokenPrice: 1.64,
    percentChange: -2.7,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/MATIC.svg',
  },
  {
    tokenTicker: 'LINK',
    tokenPrice: 15.44,
    percentChange: 2.9,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/LINK.svg',
  },
  {
    tokenTicker: 'LTC',
    tokenPrice: 123,
    percentChange: -2.7,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/LTC.svg',
  },
  {
    tokenTicker: 'CRV',
    tokenPrice: 2.84,
    percentChange: 2.2,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/CRV.svg',
  },
  {
    tokenTicker: 'SUSHI',
    tokenPrice: 4,
    percentChange: -2.1,
    contractAddress: '',
    logoUrl: 'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/assets/SUSHI.svg',
  },
]
