import { Ifo } from './types'

const ifos: Ifo[] = [
  /* {
    id: 'blink',
    address: '0x44a9Cc8463EC00937242b660BF65B10365d99baD',
    isActive: false,
    name: 'BLINk (BLK)',
    subTitle: 'Online games on BSC',
    description:
      'BLINk enables BNB holders to enjoy gaming experiences that WINk users on Tron have been enjoying for over two years.',
    launchDate: 'Nov. 20',
    launchTime: '9PM SGT',
    saleAmount: '100,000,000 BLINK',
    raiseAmount: '$1,000,000',
    bananaToBurn: '$500,000',
    projectSiteUrl: 'https://blink.wink.org',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
    tokenDecimals: 6,
    releaseBlockNumber: 3279767,
  },
  {
    id: 'ditto',
    address: '0x570c9eB19553526Fb35895a531928E19C7D20788',
    isActive: false,
    name: 'Ditto (DITTO)',
    subTitle: 'Next-gen elastic supply token',
    description:
      'Ditto is the first elastic supply token on the Binance Smart Chain. Its goal is to maintain a stable price of $1, where its supply will adapt to changes in demand. All supply changes will apply equally to every wallet holding Ditto, and holders should always have the same % of the total supply',
    launchDate: 'Dec. 23',
    launchTime: '3PM SGT',
    saleAmount: '700,000 DITTO',
    raiseAmount: '$630,000',
    bananaToBurn: '$315,000',
    projectSiteUrl: 'https://ditto.money/',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
    tokenDecimals: 9,
    releaseBlockNumber: 3279767,
  },
  {
    id: 'tenet',
    address: '0xB922aA19A2603A07C6C9ED6c236618C9bac51f06',
    isActive: false,
    name: 'Tenet (TEN)',
    subTitle: 'Cross-chain Automated Market Maker',
    description:
      'Tenet is a cross-chain Automated Market Maker (AMM) connector that provides a decentralized Liquidity Tap for various tokens. The Liquidity Tap is the powerhouse of the Liquidity Pool, employing a dynamic algorithm to give the Liquidity Provider fairer, more efficient, and richer incentives. Tenet aims to build a cross-chain and cross-platform toolkit protocol that allows the demand side to customize the parameters of the liquidity tap, allowing them to reach out to more liquidity participants effectively and with relative ease.',
    launchDate: 'Jan. 5',
    launchTime: '3PM SGT',
    saleAmount: '1,000,000 TEN',
    raiseAmount: '$1,000,000',
    bananaToBurn: '$500,000',
    projectSiteUrl: 'https://www.tenet.farm/',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
    tokenDecimals: 18,
    releaseBlockNumber: 3483883,
  },
  {
    id: 'helmet',
    address: '0xa32509d760ee47Eb2Be96D338b5d69B5FBa4eFEB',
    isActive: false,
    name: 'Helmet.insure (Helmet)',
    subTitle: 'Crypto-assets insurance trading platform',
    description:
      'Helmet is a peer-to-peer insurance protocol written with options trading logic, which allows anyone to create any insurance policy easily in the market. Helmet aims to enable DeFi users to be protected against the risk of price fluctuations by providing price-shield insurance for BSC assets. They provide suppliers with a range of insurance types to sell, giving a variety of hedging strategies to the market.',
    launchDate: 'Jan. 13',
    launchTime: '5PM SGT',
    saleAmount: '10,000,000 Helmet',
    raiseAmount: '$1,000,000',
    bananaToBurn: '$500,000',
    projectSiteUrl: 'https://www.helmet.insure/',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xA527a61703D82139F8a06Bc30097cC9CAA2df5A6',
    tokenDecimals: 18,
    releaseBlockNumber: 3771926,
  }, */
  {
    id: 'astronaut',
    address: '0xd7e98ca54e6202fb6237b98c881817ed3e54d2ed',
    isActive: false,
    name: 'Astronaut',
    subTitle: 'Decentralized hybrid yield token platform. Built on the Binance Smart Chain',
    description:
      'Protocol built for token pools and auctions enabling projects to raise capital on a decentralized and interoperable environment. Enabling the way your ideas raise capital.',
    launchDate: 'Mar. 15',
    launchTime: '11PM EDT',
    saleAmount: '2,000,000 NAUT',
    raiseAmount: '$400,000',
    bananaToBurn: '$200,000',
    projectSiteUrl: 'https://astronaut.to/',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xf65c1c0478efde3c19b49ecbe7acc57bb6b1d713',
    tokenDecimals: 8,
    releaseBlockNumber: 5685490,
  },
  {
    id: 'jediyield',
    address: '0xCBe256573185d767EfD4a797CB360880728B8fD8',
    isActive: true,
    name: 'Jedi Yield',
    subTitle: 'The only app you need for all your yield farming needs',
    description:
      'Smart portal built to increase convenience and security for BSC yield farmers. Users can freely stake and/or unstake their funds regardless of the accessibility to their favorite yield farming websites. Moreover, users can monitor their portfolios, look at token graphs, and harvest their farms all in one page',
    launchDate: 'Apr. 2',
    launchTime: '03:00 UTC',
    saleAmount: '7,000,000 JDI',
    raiseAmount: '$700,000',
    bananaToBurn: '$350,000',
    projectSiteUrl: 'https://jediyield.com/',
    currency: 'BANANA-BNB LP',
    currencyAddress: '0xf65c1c0478efde3c19b49ecbe7acc57bb6b1d713',
    tokenDecimals: 18,
    releaseBlockNumber: 6044304,
  },
]

export default ifos
