import { Nft } from './types'

const Nfts: Nft[] = [
  {
    index: 0,
    name: 'Obie Dobo',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/0.png',
    uri: '/0',
    attributes: {
      faceColor: 'Pale Pink',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Pearl',
      hats: 'Third Eye',
      rarityScore: '0.003282',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 682,
    },
  },
  {
    index: 1,
    name: 'Apeguru',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/1.png',
    uri: '/1',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Normal',
      hats: 'Astronaut',
      rarityScore: '0.004051',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 841,
    },
  },
  {
    index: 2,
    name: 'Apetastic',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/2.png',
    uri: '/2',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Pink Sunglasses',
      hats: 'Brown Hair',
      rarityScore: '0.003029',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 604,
    },
  },
  {
    index: 3,
    name: 'DKdonkiekong',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/3.png',
    uri: '/3',
    attributes: {
      faceColor: 'Green Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Happy',
      hats: 'Sweat Band',
      rarityScore: '0.006531',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 923,
    },
  },
  {
    index: 4,
    name: 'HarambeNakamoto',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/4.png',
    uri: '/4',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Gold Tooth',
      eyes: 'Shades',
      hats: 'Banana Hair',
      rarityScore: '0.000457',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 129,
    },
  },
  {
    index: 5,
    name: 'Smart Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/5.png',
    uri: '/5',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Red Sunglasses',
      hats: 'Cop',
      rarityScore: '0.003434',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 718,
    },
  },
  {
    index: 6,
    name: 'We are gonna make it',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/6.png',
    uri: '/6',
    attributes: {
      faceColor: 'Pale Pink',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Normal',
      hats: 'Brown Hair',
      rarityScore: '0.003333',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 697,
    },
  },
  {
    index: 7,
    name: 'Ape Daddy',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/7.png',
    uri: '/7',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Closed',
      hats: 'Third Eye',
      rarityScore: '0.004878',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 898,
    },
  },
  {
    index: 8,
    name: 'Ape Lord The First',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/8.png',
    uri: '/8',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Pink Sunglasses',
      hats: 'Third Eye',
      rarityScore: '0.003064',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 626,
    },
  },
  {
    index: 9,
    name: 'Diddy Kong',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/9.png',
    uri: '/9',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Orangutan',
      frames: 'Earings',
      mouths: 'Stale',
      eyes: 'Sans',
      hats: 'Brown Hair',
      rarityScore: '0.000147',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 46,
    },
  },
  {
    index: 10,
    name: 'ApeelingApe',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/10.png',
    uri: '/10',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Closed',
      hats: 'Third Eye',
      rarityScore: '0.003615',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 760,
    },
  },
  {
    index: 11,
    name: 'Forever Chimpin',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/11.png',
    uri: '/11',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Normal',
      hats: 'Third Eye',
      rarityScore: '0.003383',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 708,
    },
  },
  {
    index: 12,
    name: 'Ultimate, Diamond, Mega Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/12.png',
    uri: '/12',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Red',
      hats: 'Astronaut',
      rarityScore: '0.002700',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 464,
    },
  },
  {
    index: 13,
    name: 'Elon Musk Rides on A Banana to Mars',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/13.png',
    uri: '/13',
    attributes: {
      faceColor: 'Green Grey',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'VR Goggles',
      hats: 'Dark Cowboy',
      rarityScore: '0.002489',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 381,
    },
  },
  {
    index: 14,
    name: 'KongKyle',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/14.png',
    uri: '/14',
    attributes: {
      faceColor: 'Pale Zombie',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Red Sunglasses',
      hats: 'Banana Hair',
      rarityScore: '0.000870',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 212,
    },
  },
  {
    index: 15,
    name: 'Apegineer',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/15.png',
    uri: '/15',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'VR Goggles',
      hats: 'Cop',
      rarityScore: '0.003234',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 672,
    },
  },
  {
    index: 16,
    name: 'Banana',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/16.png',
    uri: '/16',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Red Sunglasses',
      hats: 'Pale Cowboy',
      rarityScore: '0.000678',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 185,
    },
  },
  {
    index: 17,
    name: 'Early Retirement',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/17.png',
    uri: '/17',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Closed',
      hats: 'Cop',
      rarityScore: '0.003851',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 812,
    },
  },
  {
    index: 18,
    name: 'Erwin Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/18.png',
    uri: '/18',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Pearl',
      hats: 'Sweat Band',
      rarityScore: '0.002117',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 286,
    },
  },
  {
    index: 19,
    name: 'ShouldaBeenBatman',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/19.png',
    uri: '/19',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Sans',
      hats: 'Astronaut',
      rarityScore: '0.002646',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 434,
    },
  },
  {
    index: 20,
    name: '400Unicorns Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/20.png',
    uri: '/20',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Red',
      hats: 'Banana Hair',
      rarityScore: '0.002255',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 312,
    },
  },
  {
    index: 21,
    name: 'Essential Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/21.png',
    uri: '/21',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Red Sunglasses',
      hats: 'Banana Hair',
      rarityScore: '0.003629',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 762,
    },
  },
  {
    index: 22,
    name: 'Married Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/22.png',
    uri: '/22',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Sans',
      hats: 'Banana Hair',
      rarityScore: '0.003062',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 623,
    },
  },
  {
    index: 23,
    name: 'Cold Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/23.png',
    uri: '/23',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Sans Red',
      hats: 'Visor',
      rarityScore: '0.000513',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 145,
    },
  },
  {
    index: 24,
    name: 'Everlasting Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/24.png',
    uri: '/24',
    attributes: {
      faceColor: 'Green Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Red Sunglasses',
      hats: 'Third Eye',
      rarityScore: '0.003978',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 831,
    },
  },
  {
    index: 25,
    name: 'Scornful Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/25.png',
    uri: '/25',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'VR Goggles',
      hats: 'Brown Hair',
      rarityScore: '0.002308',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 330,
    },
  },
  {
    index: 26,
    name: 'Unconscious Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/26.png',
    uri: '/26',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Red',
      hats: 'Astronaut',
      rarityScore: '0.001844',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 257,
    },
  },
  {
    index: 27,
    name: 'Flickering Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/27.png',
    uri: '/27',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Red Sunglasses',
      hats: 'Dark Cowboy',
      rarityScore: '0.004817',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 890,
    },
  },
  {
    index: 28,
    name: 'Intent Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/28.png',
    uri: '/28',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Shades',
      hats: 'Banana Hair',
      rarityScore: '0.003506',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 735,
    },
  },
  {
    index: 29,
    name: '2 Pizzas Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/29.png',
    uri: '/29',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Pearl',
      hats: 'Visor',
      rarityScore: '0.002405',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 357,
    },
  },
  {
    index: 30,
    name: 'Humble Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/30.png',
    uri: '/30',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Red Sunglasses',
      hats: 'Sweat Band',
      rarityScore: '0.002258',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 313,
    },
  },
  {
    index: 31,
    name: 'Questionable Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/31.png',
    uri: '/31',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Pearl',
      hats: 'Banana Hair',
      rarityScore: '0.005174',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 912,
    },
  },
  {
    index: 32,
    name: 'Blank Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/32.png',
    uri: '/32',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Lazer',
      hats: 'Cop',
      rarityScore: '0.001168',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 237,
    },
  },
  {
    index: 33,
    name: 'Official Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/33.png',
    uri: '/33',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Closed',
      hats: 'Dark Cowboy',
      rarityScore: '0.002656',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 438,
    },
  },
  {
    index: 34,
    name: 'Fruitful Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/34.png',
    uri: '/34',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Normal',
      hats: 'Banana Hair',
      rarityScore: '0.003338',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 700,
    },
  },
  {
    index: 35,
    name: 'Both Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/35.png',
    uri: '/35',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Pearl',
      hats: 'Astronaut',
      rarityScore: '0.002581',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 408,
    },
  },
  {
    index: 36,
    name: 'Bowed Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/36.png',
    uri: '/36',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Hazel',
      frames: 'Earings',
      mouths: 'Open',
      eyes: 'Normal',
      hats: 'Visor',
      rarityScore: '0.000128',
      rarityTierNumber: 5,
      rarityTierName: 'Magic Monkey',
      rarityOverallRank: 28,
    },
  },
  {
    index: 37,
    name: 'Paltry Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/37.png',
    uri: '/37',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Closed',
      hats: 'Red Tassle',
      rarityScore: '0.002428',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 366,
    },
  },
  {
    index: 38,
    name: 'Eminent Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/38.png',
    uri: '/38',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Closed',
      hats: 'Astronaut',
      rarityScore: '0.002731',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 479,
    },
  },
  {
    index: 39,
    name: 'Enchanting Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/39.png',
    uri: '/39',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Red Sunglasses',
      hats: 'Red Tassle',
      rarityScore: '0.004092',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 846,
    },
  },
  {
    index: 40,
    name: 'Thorny Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/40.png',
    uri: '/40',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Red Sunglasses',
      hats: 'Red Tassle',
      rarityScore: '0.002615',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 422,
    },
  },
  {
    index: 41,
    name: 'Apt Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/41.png',
    uri: '/41',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Pink Sunglasses',
      hats: 'Astronaut',
      rarityScore: '0.002746',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 486,
    },
  },
  {
    index: 42,
    name: 'Grand Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/42.png',
    uri: '/42',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'VR Goggles',
      hats: 'Dark Cowboy',
      rarityScore: '0.002823',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 516,
    },
  },
  {
    index: 43,
    name: 'Hateful Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/43.png',
    uri: '/43',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Pearl',
      hats: 'Sweat Band',
      rarityScore: '0.002445',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 371,
    },
  },
  {
    index: 44,
    name: 'Lighthearted Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/44.png',
    uri: '/44',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Pearl',
      hats: 'Sweat Band',
      rarityScore: '0.002141',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 289,
    },
  },
  {
    index: 45,
    name: 'Bite-Sized Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/45.png',
    uri: '/45',
    attributes: {
      faceColor: 'Pale Pink',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Happy',
      hats: 'Banana Hair',
      rarityScore: '0.009741',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 971,
    },
  },
  {
    index: 46,
    name: 'Unnatural Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/46.png',
    uri: '/46',
    attributes: {
      faceColor: 'Pale Pink',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Closed',
      hats: 'Astronaut',
      rarityScore: '0.003975',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 830,
    },
  },
  {
    index: 47,
    name: 'Old-Fashioned Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/47.png',
    uri: '/47',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Normal',
      hats: 'Sweat Band',
      rarityScore: '0.002188',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 297,
    },
  },
  {
    index: 48,
    name: 'Precious Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/48.png',
    uri: '/48',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Maroon',
      frames: 'Earings',
      mouths: 'Sad',
      eyes: 'VR Goggles',
      hats: 'Brown Hair',
      rarityScore: '0.000141',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 38,
    },
  },
  {
    index: 49,
    name: 'Trim Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/49.png',
    uri: '/49',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Shades',
      hats: 'Sweat Band',
      rarityScore: '0.002931',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 570,
    },
  },
  {
    index: 50,
    name: 'Frugal Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/50.png',
    uri: '/50',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Red',
      hats: 'Sweat Band',
      rarityScore: '0.001853',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 258,
    },
  },
  {
    index: 51,
    name: 'Lawful Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/51.png',
    uri: '/51',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Shades',
      hats: 'Astronaut',
      rarityScore: '0.002824',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 518,
    },
  },
  {
    index: 52,
    name: 'Cultivated Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/52.png',
    uri: '/52',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Happy',
      hats: 'Cop',
      rarityScore: '0.012782',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 996,
    },
  },
  {
    index: 53,
    name: 'Austere Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/53.png',
    uri: '/53',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'VR Goggles',
      hats: 'Cop',
      rarityScore: '0.004533',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 879,
    },
  },
  {
    index: 54,
    name: 'Icy Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/54.png',
    uri: '/54',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'VR Goggles',
      hats: 'Banana Hair',
      rarityScore: '0.004820',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 891,
    },
  },
  {
    index: 55,
    name: 'Cooked Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/55.png',
    uri: '/55',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Sans Red',
      hats: 'Astronaut',
      rarityScore: '0.000600',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 166,
    },
  },
  {
    index: 56,
    name: 'Loathsome Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/56.png',
    uri: '/56',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Red Sunglasses',
      hats: 'Sweat Band',
      rarityScore: '0.002849',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 533,
    },
  },
  {
    index: 57,
    name: 'Idle Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/57.png',
    uri: '/57',
    attributes: {
      faceColor: 'Pale Zombie',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Normal',
      hats: 'Third Eye',
      rarityScore: '0.000753',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 198,
    },
  },
  {
    index: 58,
    name: 'Unfortunate Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/58.png',
    uri: '/58',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Army Green',
      frames: 'Earings',
      mouths: 'Open',
      eyes: 'Closed',
      hats: 'Dark Cowboy',
      rarityScore: '0.000145',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 41,
    },
  },
  {
    index: 59,
    name: 'Esteemed Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/59.png',
    uri: '/59',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Pearl',
      hats: 'Red Tassle',
      rarityScore: '0.002426',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 364,
    },
  },
  {
    index: 60,
    name: 'Acclaimed Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/60.png',
    uri: '/60',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Orangutan',
      frames: 'Earings',
      mouths: 'Stale',
      eyes: 'Normal',
      hats: 'Sweat Band',
      rarityScore: '0.000141',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 39,
    },
  },
  {
    index: 61,
    name: 'Monumental Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/61.png',
    uri: '/61',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Pearl',
      hats: 'Banana Hair',
      rarityScore: '0.003164',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 654,
    },
  },
  {
    index: 62,
    name: 'Icebergy Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/62.png',
    uri: '/62',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Closed',
      hats: 'Cop',
      rarityScore: '0.003411',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 715,
    },
  },
  {
    index: 63,
    name: 'Scented Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/63.png',
    uri: '/63',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Grape Purple',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Pink Sunglasses',
      hats: 'Dark Cowboy',
      rarityScore: '0.000516',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 146,
    },
  },
  {
    index: 64,
    name: 'Mediocre Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/64.png',
    uri: '/64',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Open Smile',
      eyes: 'Red',
      hats: 'Astronaut',
      rarityScore: '0.000357',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 84,
    },
  },
  {
    index: 65,
    name: 'Optimistic Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/65.png',
    uri: '/65',
    attributes: {
      faceColor: 'Green Grey',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Normal',
      hats: 'Brown Hair',
      rarityScore: '0.002279',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 321,
    },
  },
  {
    index: 66,
    name: 'Organic Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/66.png',
    uri: '/66',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Lazer',
      hats: 'Banana Hair',
      rarityScore: '0.001007',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 228,
    },
  },
  {
    index: 67,
    name: 'Lazy Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/67.png',
    uri: '/67',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Normal',
      hats: 'Red Tassle',
      rarityScore: '0.003778',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 795,
    },
  },
  {
    index: 68,
    name: 'Bewitched Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/68.png',
    uri: '/68',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'VR Goggles',
      hats: 'Dark Cowboy',
      rarityScore: '0.002745',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 484,
    },
  },
  {
    index: 69,
    name: 'Decisive Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/69.png',
    uri: '/69',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Pink Sunglasses',
      hats: 'Banana Hair',
      rarityScore: '0.003130',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 639,
    },
  },
  {
    index: 70,
    name: 'Obedient Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/70.png',
    uri: '/70',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Lazer',
      hats: 'Red Tassle',
      rarityScore: '0.001309',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 242,
    },
  },
  {
    index: 71,
    name: 'Cryptobethany Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/71.png',
    uri: '/71',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'VR Goggles',
      hats: 'Astronaut',
      rarityScore: '0.003133',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 640,
    },
  },
  {
    index: 72,
    name: 'Inferior Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/72.png',
    uri: '/72',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Normal',
      hats: 'Astronaut',
      rarityScore: '0.003102',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 634,
    },
  },
  {
    index: 73,
    name: 'Nonstop Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/73.png',
    uri: '/73',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Open Smile',
      eyes: 'Red',
      hats: 'Third Eye',
      rarityScore: '0.000362',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 86,
    },
  },
  {
    index: 74,
    name: 'Accurate Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/74.png',
    uri: '/74',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Closed',
      hats: 'Avatar',
      rarityScore: '0.000687',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 188,
    },
  },
  {
    index: 75,
    name: 'Near Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/75.png',
    uri: '/75',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Shades',
      hats: 'Banana Hair',
      rarityScore: '0.003865',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 814,
    },
  },
  {
    index: 76,
    name: 'Embellished Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/76.png',
    uri: '/76',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Red',
      hats: 'Brown Hair',
      rarityScore: '0.001983',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 270,
    },
  },
  {
    index: 77,
    name: 'Criminal Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/77.png',
    uri: '/77',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Red',
      hats: 'Pale Cowboy',
      rarityScore: '0.000923',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 224,
    },
  },
  {
    index: 78,
    name: 'Necessary Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/78.png',
    uri: '/78',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Normal',
      hats: 'Visor',
      rarityScore: '0.002357',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 344,
    },
  },
  {
    index: 79,
    name: 'Mature Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/79.png',
    uri: '/79',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Happy',
      hats: 'Dark Cowboy',
      rarityScore: '0.011326',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 989,
    },
  },
  {
    index: 80,
    name: 'Enchanted Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/80.png',
    uri: '/80',
    attributes: {
      faceColor: 'Pale Pink',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Gold Tooth',
      eyes: 'Red',
      hats: 'Third Eye',
      rarityScore: '0.000351',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 83,
    },
  },
  {
    index: 81,
    name: 'Insistent Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/81.png',
    uri: '/81',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Pearl',
      hats: 'Dark Cowboy',
      rarityScore: '0.002809',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 512,
    },
  },
  {
    index: 82,
    name: 'Tubby Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/82.png',
    uri: '/82',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Albino',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Normal',
      hats: 'Cop',
      rarityScore: '0.000428',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 117,
    },
  },
  {
    index: 83,
    name: 'Tough Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/83.png',
    uri: '/83',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Gold Tooth',
      eyes: 'Sans',
      hats: 'Brown Hair',
      rarityScore: '0.000404',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 104,
    },
  },
  {
    index: 84,
    name: 'Prize Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/84.png',
    uri: '/84',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Sans',
      hats: 'Avatar',
      rarityScore: '0.000534',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 152,
    },
  },
  {
    index: 85,
    name: 'Quirky Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/85.png',
    uri: '/85',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Maroon',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Happy',
      hats: 'Dark Cowboy',
      rarityScore: '0.008001',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 950,
    },
  },
  {
    index: 86,
    name: 'Linear Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/86.png',
    uri: '/86',
    attributes: {
      faceColor: 'Green Grey',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Red',
      hats: 'Third Eye',
      rarityScore: '0.003819',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 804,
    },
  },
  {
    index: 87,
    name: 'Decent Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/87.png',
    uri: '/87',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'VR Goggles',
      hats: 'Banana Hair',
      rarityScore: '0.003511',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 736,
    },
  },
  {
    index: 88,
    name: 'Good-Natured Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/88.png',
    uri: '/88',
    attributes: {
      faceColor: 'Blood Orange',
      baseColor: 'Army Green',
      frames: 'Earings',
      mouths: 'Stale',
      eyes: 'Pink Sunglasses',
      hats: 'Brown Hair',
      rarityScore: '0.000138',
      rarityTierNumber: 4,
      rarityTierName: 'Prime Primate',
      rarityOverallRank: 34,
    },
  },
  {
    index: 89,
    name: 'Jumpy Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/89.png',
    uri: '/89',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Sans',
      hats: 'Visor',
      rarityScore: '0.002408',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 358,
    },
  },
  {
    index: 90,
    name: 'Giving Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/90.png',
    uri: '/90',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Hazel',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Red Sunglasses',
      hats: 'Sweat Band',
      rarityScore: '0.002969',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 587,
    },
  },
  {
    index: 91,
    name: 'Loyal Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/91.png',
    uri: '/91',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Buck Teeth',
      eyes: 'Pearl',
      hats: 'Pale Cowboy',
      rarityScore: '0.000622',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 171,
    },
  },
  {
    index: 92,
    name: 'Fickle Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/92.png',
    uri: '/92',
    attributes: {
      faceColor: 'Burnt Orange',
      baseColor: 'Zombie Purple',
      frames: 'Main Frame',
      mouths: 'Open Smile',
      eyes: 'Pearl',
      hats: 'Third Eye',
      rarityScore: '0.000504',
      rarityTierNumber: 3,
      rarityTierName: 'Alluring Ape',
      rarityOverallRank: 143,
    },
  },
  {
    index: 93,
    name: 'Dearest Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/93.png',
    uri: '/93',
    attributes: {
      faceColor: 'Smoke Grey',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Sad',
      eyes: 'Sans',
      hats: 'Dark Cowboy',
      rarityScore: '0.002488',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 380,
    },
  },
  {
    index: 94,
    name: 'Quarrelsome Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/94.png',
    uri: '/94',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Sans',
      hats: 'Sweat Band',
      rarityScore: '0.002355',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 343,
    },
  },
  {
    index: 95,
    name: 'Abandoned Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/95.png',
    uri: '/95',
    attributes: {
      faceColor: 'Brown',
      baseColor: 'Army Green',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Closed',
      hats: 'Cop',
      rarityScore: '0.002646',
      rarityTierNumber: 2,
      rarityTierName: 'Original Orangutan',
      rarityOverallRank: 435,
    },
  },
  {
    index: 96,
    name: 'Uncomfortable Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/96.png',
    uri: '/96',
    attributes: {
      faceColor: 'Moon Blue',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Happy',
      eyes: 'Pink Sunglasses',
      hats: 'Cop',
      rarityScore: '0.004394',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 871,
    },
  },
  {
    index: 97,
    name: 'Handsome Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/97.png',
    uri: '/97',
    attributes: {
      faceColor: 'ApeSwap Brown',
      baseColor: 'Orangutan',
      frames: 'Main Frame',
      mouths: 'Open',
      eyes: 'Happy',
      hats: 'Sweat Band',
      rarityScore: '0.007255',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 930,
    },
  },
  {
    index: 98,
    name: 'Naive Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/98.png',
    uri: '/98',
    attributes: {
      faceColor: 'Ripe Banana',
      baseColor: 'Dark Grey',
      frames: 'Main Frame',
      mouths: 'Stale',
      eyes: 'Pearl',
      hats: 'Astronaut',
      rarityScore: '0.003253',
      rarityTierNumber: 1,
      rarityTierName: 'Common Chimp',
      rarityOverallRank: 675,
    },
  },
  {
    index: 99,
    name: 'Liquid Ape',
    image: 'https://raw.githubusercontent.com/ApeSwapFinance/non-fungible-apes/main/images/99.png',
    uri: '/99',
    attributes: {
      faceColor: 'Highlighter Blue',
      baseColor: 'Dark Grey',
      frames: 'Earings',
      mouths: 'Buck Teeth',
      eyes: 'Red Sunglasses',
      hats: 'Sweat Band',
      rarityScore: '0.000129',
      rarityTierNumber: 5,
      rarityTierName: 'Magic Monkey',
      rarityOverallRank: 29,
    },
  },
]

export default Nfts
